import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Linktree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[conic-gradient(var(--tw-gradient-stops))] from-slate-900 via-green-800 to-purple-900 min-h-full">
        {children}
      </body>
    </html>
  );
}
